![Numpy](https://i0.wp.com/www.ozgurozkok.com/wp-content/uploads/2019/12/numpy-python.png?fit=765%2C306&ssl=1)

NumPy is a powerful Python library for numerical computing. It stands for "Numerical Python" and provides efficient mechanisms to perform mathematical and logical operations on arrays or large multidimensional data sets.

Here are some reasons why NumPy is widely used:

1. **Efficient array operations**: NumPy provides an `ndarray` (n-dimensional array) object that allows you to perform fast computations on large datasets efficiently. The underlying implementation of NumPy arrays is written in C, which makes it faster than using built-in Python data structures like lists.

2. **Vectorized operations**: NumPy enables vectorized operations, which means performing operations on entire arrays rather than looping through individual elements. This approach significantly improves computation speed and code readability.

3. **Broad range of mathematical functions**: NumPy offers a wide range of mathematical functions, such as trigonometric functions, exponential functions, linear algebra operations, statistical functions, and more. These functions are optimized for performance and can handle arrays as inputs, making complex numerical computations easier.

4. **Memory efficiency**: NumPy arrays require less memory compared to Python lists. This efficiency is due to the homogeneous type of elements in an array, which allows for better memory allocation and utilization.

5. **Integration with other libraries**: NumPy serves as the foundation for many other scientific computing and data analysis libraries in Python, such as SciPy (scientific computing), pandas (data manipulation), scikit-learn (machine learning), and matplotlib (plotting). These libraries often rely on NumPy arrays as a common data structure, allowing seamless integration and interoperability.

Overall, NumPy's simplicity, speed, and extensive functionality make it an essential tool for scientific computing, numerical analysis, and data manipulation tasks in Python.


# let`s have some fun by writeing code

In [2]:
import numpy as np

# DataTypes % Attributes

The main data type used in NumPy is the `ndarray` (n-dimensional array) object. This object represents a multidimensional, homogeneous array of fixed-size items. The elements within an `ndarray` are typically numbers (integers, floats) but can also be other data types like booleans or strings.

NumPy provides several built-in data types that you can use when creating arrays, including:

- **integers**: `int8`, `int16`, `int32`, `int64`, `uint8`, `uint16`, `uint32`, `uint64`
- **floating-point numbers**: `float16`, `float32`, `float64`
- **complex numbers**: `complex64`, `complex128`
- **booleans**: `bool`
- **strings**: `str`

You can specify the data type when creating an array using the `dtype` parameter. For example, to create an array of integers, you can use `numpy.array([...], dtype=int)`.

By default, if a data type is not explicitly specified, NumPy will infer the data type based on the values provided. For example, if you pass a list of integers to create an array, NumPy will assign the `int64` data type to the array.

Using appropriate data types in NumPy arrays allows for efficient memory usage and optimized computational performance. You can also perform various mathematical and logical operations on arrays with different data types, as NumPy handles automatic type conversion when necessary.


In [3]:
a1 = np.array([1,2,3,4])
a1

array([1, 2, 3, 4])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1,2.3,3.3],
                [4,5.6,7.8]])

a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
               [[10,11,12],
                [13,14,15],
                [16,17,18]
               ]])

In [6]:
a2

array([[1. , 2.3, 3.3],
       [4. , 5.6, 7.8]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

![anatomy of a numpy array](numpy-anatomy-of-an-array-updated.png)

In [9]:
a1.shape

(4,)

In [10]:
a2.shape

(2, 3)

In [11]:
a3.shape

(2, 3, 3)

In [12]:
a1.ndim , a2.ndim , a3.ndim

(1, 2, 3)

In [13]:
a1.dtype , a2.dtype , a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [14]:
a1.size , a2.size , a3.size

(4, 6, 18)

In [15]:
type(a1) , type(a2) , type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

# Create a DataFrame from a numpy array 

In [18]:
import pandas as pd 
dp = pd.DataFrame(a2)

In [19]:
dp

0    1    2
0  1.0  2.3  3.3
1  4.0  5.6  7.8

# 2 Createing numpy arrays 

In [20]:
sample_array = np.array([1,2,3,4,5,6,7])
sample_array

array([1, 2, 3, 4, 5, 6, 7])

In [21]:
sample_array.dtype

dtype('int32')

In [22]:
# what is ones() 
# Signature: np.ones(shape, dtype=None, order='C', *, like=None)
# Docstring:
# Return a new array of given shape and type, filled with ones.
ones = np.ones((2,3))

In [23]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
ones.dtype

dtype('float64')

In [25]:
type(ones)

numpy.ndarray

In [26]:
zeros = np.zeros((2,3))

In [27]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [30]:
random_array = np.random.randint(0,10 , size=(3,5))

In [31]:
random_array

array([[3, 2, 7, 9, 3],
       [9, 5, 5, 4, 0],
       [0, 1, 2, 5, 1]])

In [32]:
random_array.size

15

In [33]:
random_array.shape

(3, 5)

In [35]:
random_array_2 =  np.random.random((5,3))
random_array_2

array([[0.44331227, 0.51503014, 0.43072236],
       [0.37472011, 0.5890353 , 0.50093851],
       [0.8682029 , 0.30189261, 0.18825259],
       [0.86008427, 0.10538799, 0.52925097],
       [0.02361121, 0.19452401, 0.42481604]])

In [36]:
random_array_2.shape

(5, 3)

In [37]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.68093627, 0.00456693, 0.21074756],
       [0.12145168, 0.95355744, 0.10688254],
       [0.91867184, 0.55429314, 0.81236283],
       [0.01554035, 0.98768174, 0.43019453],
       [0.83303057, 0.79568959, 0.11637072]])

In [42]:
 np.random.seed(6)

random_array_4 = np.random.randint(10 , size=(5,3))
random_array_4

array([[9, 3, 4],
       [0, 9, 1],
       [9, 1, 4],
       [1, 8, 2],
       [4, 2, 5]])

In [44]:
random_array_4 = np.random.randint(10 , size=(5,3))
random_array_4

array([[2, 7, 8],
       [5, 6, 3],
       [5, 1, 2],
       [3, 6, 9],
       [9, 8, 0]])

In [39]:
random_array_4.shape

(5, 3)

np.random.seed() is a function provided by the NumPy library in Python. It is used to set the seed value for the random number generator in NumPy. The random number generator is responsible for generating pseudo-random numbers.

By setting the seed value using np.random.seed(), you can ensure that the sequence of random numbers generated by NumPy is reproducible. This means that if you set the same seed value, you will get the same sequence of random numbers every time you run the program.

# 3- Viewing arras and matrices

In [46]:
random_array_4

array([[2, 7, 8],
       [5, 6, 3],
       [5, 1, 2],
       [3, 6, 9],
       [9, 8, 0]])

In [47]:
np.unique(random_array_4)

array([0, 1, 2, 3, 5, 6, 7, 8, 9])

In [48]:
a1[0]

1

In [49]:
a2[0]

array([1. , 2.3, 3.3])

In [50]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
a1.shape , a2.shape, a3.shape

((4,), (2, 3), (2, 3, 3))

In [52]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [53]:
a3[:2 , :2 , :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [54]:
a4 = np.random.randint(10 , size=(2,3,4,5))
a4

array([[[[3, 7, 4, 8, 1],
         [2, 4, 1, 5, 5],
         [6, 1, 9, 0, 5],
         [8, 9, 1, 2, 2]],

        [[9, 5, 4, 1, 6],
         [3, 1, 4, 9, 8],
         [4, 6, 2, 9, 6],
         [2, 5, 2, 7, 5]],

        [[1, 1, 7, 5, 4],
         [2, 8, 8, 7, 8],
         [0, 8, 9, 2, 0],
         [7, 6, 0, 7, 5]]],


       [[[1, 8, 5, 9, 6],
         [3, 7, 7, 5, 3],
         [8, 7, 3, 5, 9],
         [3, 8, 0, 7, 7]],

        [[0, 3, 5, 3, 2],
         [3, 4, 9, 0, 8],
         [6, 3, 2, 1, 6],
         [8, 8, 9, 0, 7]],

        [[6, 0, 1, 8, 5],
         [9, 8, 5, 9, 1],
         [1, 2, 9, 9, 5],
         [6, 4, 0, 4, 2]]]])

In [55]:
a4.shape

(2, 3, 4, 5)

In [56]:
a3.ndim

3

In [58]:
a4[: , : , : ,:1]

array([[[[3],
         [2],
         [6],
         [8]],

        [[9],
         [3],
         [4],
         [2]],

        [[1],
         [2],
         [0],
         [7]]],


       [[[1],
         [3],
         [8],
         [3]],

        [[0],
         [3],
         [6],
         [8]],

        [[6],
         [9],
         [1],
         [6]]]])